name: "Zen Agents Action"
description: "A GitHub Action to run Zencoder Autonomous Agents"
inputs:
  prompt:
    description: "The input prompt for the Agent"
    required: true
  agent:
    description: "Alias of the agent to run (will run default agent if not provided)"
    required: false
    default: ""
  base_path:
    description: "Base path to run agent from (should be repository root)"
    required: false
    default: "."
  zencoder_client_id:
    description: "Client ID for Zencoder API"
    required: true
  zencoder_client_secret:
    description: "Client Secret for Zencoder API"
    required: true
  github_token:
    description: "GitHub token used by the action to access GitHub APIs"
    required: true
  version:
    description: "Version of the zencoder cli to use"
    required: false
    default: latest
  model:
    description: "LLM model to use (e.g., opus-4-5, sonnet-4, gemini-25-pro). Use 'default' for server default."
    required: false
    default: "default"

runs:
  using: "composite"
  steps:
    - name: Install zencoder
      shell: bash
      run: |
        ZEN_CLI_NAME="zencoder"
        BASE_URL="https://storage.googleapis.com/zencoder-public/zencoder/linux-amd64/${{ inputs.version }}"
        
        echo "Downloading $ZEN_CLI_NAME..."
        curl -fsSL -o $ZEN_CLI_NAME "$BASE_URL/$ZEN_CLI_NAME" || {
          echo "Error: Failed to download zencoder binary" >&2
          exit 1
        }
        
        if [ ! -s $ZEN_CLI_NAME ]; then
          echo "Error: Downloaded file is empty or missing" >&2
          exit 1
        fi
        
        echo "Downloading checksum..."
        curl -fsSL -o ${ZEN_CLI_NAME}.sha256 "$BASE_URL/${ZEN_CLI_NAME}.sha256" || {
          echo "Error: Failed to download checksum file" >&2
          exit 1
        }
        
        echo "Verifying integrity..."
        echo "$(cat ${ZEN_CLI_NAME}.sha256)  $ZEN_CLI_NAME" | sha256sum -c - || {
          echo "Error: Checksum verification failed" >&2
          exit 1
        }
        
        chmod +x $ZEN_CLI_NAME
        echo "Successfully installed and verified $ZEN_CLI_NAME"

    - name: Run Zen Agent
      shell: bash
      env:
        PROMPT: "${{ inputs.prompt }}"
        AGENT: "${{ inputs.agent }}"
        BASE_PATH: "${{ inputs.base_path }}"
        MODEL: "${{ inputs.model }}"
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CLIENT_ID: ${{ inputs.zencoder_client_id }}
        CLIENT_SECRET: ${{ inputs.zencoder_client_secret }}
      run: |
        MODEL_ARG=""
        if [ -n "$MODEL" ] && [ "$MODEL" != "default" ]; then
          MODEL_ARG="--model $MODEL"
        fi
        ./zencoder --base-path "$BASE_PATH" --agent "$AGENT" $MODEL_ARG --prompt "$PROMPT" --autonomous